# Generated by Django 3.1.2 on 2022-05-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/thumbnail/'),
            preserve_default=False,
        ),
    ]
